[package]
name = "rutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
md5 = "0.7.0"
wasm-bindgen = "0.2.84"

[profile.release]
opt-level = "s"
